export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FINISHED = 'SIGNUP_FINISHED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const PROFILE_DETAIL = 'PROFILE_DETAIL';

export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';


export const USER_FORM_FILLUP = 'USER_FORM_FILLUP'
export const USER_FORM_FILLUP_ALL = 'USER_FORM_FILLUP_ALL'
export const FORM_FILLUP_DONE = 'FORM_FILLUP_DONE'
